### ISSUE TITLE
Missing "type": "module" in package.json

### ISSUE THREAD

**Issue by webhype** [nokazn/strip-json-trailing-commas#3]
The sub module "esm" is written as a module, not as common JS (it uses export ... )

However, the overall project, as it is on npm right now, is published as common JS module.

After $ npm i strip-json-trailing-commas I had to go into node_modules/strip-json-trailing-commas/package.json and had to add "type": "module" to the top level of package.json, which apparently fixed it.

**Comment by nokazn** [comment]
@webhype
Thank you for reporting this issue. This will be resolved by #4, I think.
